### PR TITLE
issue #2213: add attachments fields

### PR DESCRIPTION
**Pull request by mikhalev-im**

### CODE REVIEW

**Comment by patrickd-** [comment]
* please adjust changelog
* "Reply will always have either `text` or `attachments`." – i don't think this is true since the attachment.noText option has not been implemented it can have both?

**Comment by mikhalev-im** [comment]
> please adjust changelog

I just thought [this](
https://github.com/socialhubio/socialhub-dev/blob/master/docs/changelog.md#new-reply-attachments) note already announces reply attachments so it could be left as is?

> i don't think this is true since the attachment.noText option has not been implemented it can have both?

What I tried to say is that `text` is optional if there is an `attachments` field and the `attachments`  field is optional if there is a `text`, but there are always should be at least one of those. Maybe I need to write it differently to make it more clear

**Comment by patrickd-** [comment]
* that note only mentions the manifest change at the moment
* either-or to me means it's mutually exclusive

**Comment by mikhalev-im** [comment]
@patrickd- updated

**Pull request merged**
